[package]
name = "tupy"
version = "0.1.0"
edition = "2021"

[[example]]
name="user"
required-features = ["env-file"]

[[bin]]
name = "tupy"
path = "src/main.rs"
required-features = ["env-file"]

[features]
defaults = ["cli"]
env-file = ["dep:dotenvy"]
cli = []
future = []

[dev-dependencies]
dialoguer = { version = "0.11.0", features = ["fuzzy-matcher", "fuzzy-select"] }

[dependencies]
base64 = "0.22.1"
chrono = "0.4.38"
dialoguer = { version = "0.11.0", features = ["fuzzy-matcher", "fuzzy-select"] }
dirs = "5.0.1"
dotenvy = { version = "0.15.7", optional = true }

env_logger = "0.11.3"
getrandom = "0.2.15"
http-body-util = "0.1.2"
hyper = { version = "1.3.1", features = ["http1", "server"] }
hyper-util = { version = "0.1.5", features = ["http1", "server"] }
indoc = "2.0.5"
log = "0.4.21"
open = "5.1.4"
paste = "1.0.15"
reqwest = "0.12.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
serde_path_to_error = "0.1.16"
serde_qs = "0.13.0"
serde_urlencoded = "0.7.1"
sha2 = "0.10.8"
strum = { version = "0.26.3", features = ["strum_macros", "derive", "phf"] }
strum_macros = "0.26.4"
tokio = { version = "1.38.0", features = ["rt-multi-thread", "net", "signal", "signal-hook-registry", "time", "macros", "fs", "bytes"] }
uuid = { version = "1.8.0", features = ["v4", "serde", "fast-rng"] }
