[package]
name = "rataify"
version = "0.1.0"
edition = "2021"

[dependencies]
tupy = { path = "./crates/tupy/", features = ["env-file", "caching"] }

color-eyre = "0.6.3"
crossterm = { version = "0.27.0", features = ["event-stream", "serde"] }
futures = "0.3.30"
ratatui = { version = "0.27.0", features = ["macros", "serde"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
tokio = { version = "1.38.0", features = ["full"] }
tokio-util = "0.7.11"

# Self host automatic spotify authentication
http-body-util = "0.1.2"
hyper = { version = "1.3.1", features = ["http1", "server"] }
hyper-util = { version = "0.1.5", features = ["http1", "server"] }
indoc = "2.0.5"
serde_qs = "0.13.0"
open = "5.1.4"
log = "0.4.22"
