workspace = { members = ["crates/rotify"] }
[package]
name = "rataify"
version = "0.1.0"
edition = "2021"

# Optimized backtrace for color_eyre in debug mode
[profile.dev.package.backtrace]
opt-level = 3

[dependencies.rotify]
path = "crates/rotify"
features = [
    'user-read-playback-state',
    'user-read-currently-playing',
    'user-modify-playback-state',
]

[dependencies]
# Terminal Interaction
crossterm = { version = "0.27.0", features = ["event-stream", "serde"] }
ratatui = "0.26.1"
dialoguer = "0.11.0"
clap = "4.5.1"

# Error handling
color-eyre = "0.6.2"

# Async + HTTP
tokio = { version = "1.36.0", features = ["full"] }
tokio-util = "0.7.10"
futures = "0.3.30"
hyper = { version="1", features = ["full"] }
hyper-util = { version = "0.1.3", features = ["full"] }
http-body-util = "0.1.0"

urlencoding = "2.1.3"
lazy_static = "1.4.0"
open = "5.0.1"
regex = "1.10.3"

# Serde
serde = { version = "1.0.197", features = ["derive"] }
serde_qs = "0.12.0"
serde_yaml = "0.9.32"
serde_json = "1.0.114"
serde_urlencoded = "0.7.1"
serde_path_to_error = "0.1.15"

# Environment
envy = "0.4.2"
dotenvy = "0.15.7"

html-to-string-macro = "0.2.5"
rand = "0.8.5"
uuid = { version = "1.7.0", features = ["v4"] }
base64 = "0.21.7"
reqwest = { version = "0.11.24", features = ["json"] }
chrono = { version = "0.4.34", features = ["serde"] }
home = "0.5.9"
rspotify = { version = "0.12.0", features = ["cli"] }
env_logger = "0.11.2"
