extern crate rataify;

use rataify::spotify::api::{Item, Track};

const source: &'static str = r#"{
  "album": {
    "album_type": "album",
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/2hmePXeTr2b7cdRAtRjvPq"
        },
        "href": "https://api.spotify.com/v1/artists/2hmePXeTr2b7cdRAtRjvPq",
        "id": "2hmePXeTr2b7cdRAtRjvPq",
        "name": "Jeris Johnson",
        "type": "artist",
        "uri": "spotify:artist:2hmePXeTr2b7cdRAtRjvPq"
      }
    ],
    "available_markets": [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
    ],
    "external_urls": {
      "spotify": "https://open.spotify.com/album/4KkTFPZPuyOWmBNuUXrD0e"
    },
    "href": "https://api.spotify.com/v1/albums/4KkTFPZPuyOWmBNuUXrD0e",
    "id": "4KkTFPZPuyOWmBNuUXrD0e",

    "images": [
      {
        "height": 640,
        "url": "https://i.scdn.co/image/ab67616d0000b273814ef17c9a3e8aeb174d0e96",
        "width": 640
      },
      {
        "height": 300,
        "url": "https://i.scdn.co/image/ab67616d00001e02814ef17c9a3e8aeb174d0e96",
        "width": 300
      },
      {
        "height": 64,
        "url": "https://i.scdn.co/image/ab67616d00004851814ef17c9a3e8aeb174d0e96",
        "width": 64
      }
    ],
    "name": "I WANT BLOOD / i want love",
    "release_date": "2022-02-03",
    "release_date_precision": "day",
    "total_tracks": 11,
    "type": "album",
    "uri": "spotify:album:4KkTFPZPuyOWmBNuUXrD0e"
  },
  "artists": [
    {
      "external_urls": {
        "spotify": "https://open.spotify.com/artist/2hmePXeTr2b7cdRAtRjvPq"
      },
      "href": "https://api.spotify.com/v1/artists/2hmePXeTr2b7cdRAtRjvPq",

      "id": "2hmePXeTr2b7cdRAtRjvPq",
      "name": "Jeris Johnson",
      "type": "artist",
      "uri": "spotify:artist:2hmePXeTr2b7cdRAtRjvPq"
    }
  ],
  "available_markets": [
    "AR",
    "AU",
    "AT",
    "BE",
    "BO",
    "BR",
    "BG",
    "CA",
    "CL",
    "CO",
    "CR",
    "CY",
    "CZ",
    "DK",
    "DO",
    "DE",
    "EC",
    "EE",
    "SV",
    "FI",
    "FR",
    "GR",
    "GT",
    "HN",
    "HK",
    "HU",
    "IS",
    "IE",
    "IT",
    "LV",
    "LT",
    "LU",
    "MY",
    "MT",
    "MX",
    "NL",
    "NZ",
    "NI",
    "NO",
    "PA",
    "PY",
    "PE",
    "PH",
    "PL",
    "PT",
    "SG",
    "SK",
    "ES",
    "SE",
    "CH",
    "TW",
    "TR",
    "UY",
    "US",
    "GB",
    "AD",
    "LI",
    "MC",
    "ID",
    "JP",
    "TH",
    "VN",
    "RO",
    "IL",
    "ZA",
    "SA",
    "AE",
    "BH",
    "QA",
    "OM",
    "KW",
    "EG",
    "MA",
    "DZ",
    "TN",
    "LB",
    "JO",
    "PS",
    "IN",
    "BY",
    "KZ",
    "MD",
    "UA",
    "AL",
    "BA",
    "HR",
    "ME",
    "MK",
    "RS",
    "SI",
    "KR",
    "BD",
    "PK",
    "LK",
    "GH",
    "KE",
    "NG",
    "TZ",
    "UG",
    "AG",
    "AM",
    "BS",
    "BB",
    "BZ",
    "BT",
    "BW",
    "BF",
    "CV",
    "CW",
    "DM",
    "FJ",
    "GM",
    "GE",
    "GD",
    "GW",
    "GY",
    "HT",
    "JM",
    "KI",
    "LS",
    "LR",
    "MW",
    "MV",
    "ML",
    "MH",
    "FM",
    "NA",
    "NR",
    "NE",
    "PW",
    "PG",
    "WS",
    "SM",
    "ST",
    "SN",
    "SC",
    "SL",
    "SB",
    "KN",
    "LC",
    "VC",
    "SR",
    "TL",
    "TO",
    "TT",
    "TV",
    "VU",
    "AZ",
    "BN",
    "BI",
    "KH",
    "CM",
    "TD",
    "KM",
    "GQ",
    "SZ",
    "GA",
    "GN",
    "KG",
    "LA",
    "MO",
    "MR",
    "MN",
    "NP",
    "RW",
    "TG",
    "UZ",
    "ZW",
    "BJ",
    "MG",
    "MU",
    "MZ",
    "AO",
    "CI",
    "DJ",
    "ZM",
    "CD",
    "CG",
    "IQ",
    "LY",
    "TJ",
    "VE",
    "ET",
    "XK"
  ],
  "disc_number": 1,
  "duration_ms": 119050,
  "explicit": false,
  "external_ids": {
    "isrc": "QMCE32200017"
  },
  "external_urls": {
    "spotify": "https://open.spotify.com/track/2MJADWCUllbjr5dtgwQDrw"
  },
  "href": "https://api.spotify.com/v1/tracks/2MJADWCUllbjr5dtgwQDrw",
  "id": "2MJADWCUllbjr5dtgwQDrw",
  "is_local": false,
  "name": "CHOKEHOLD",
  "popularity": 40,
  "preview_url": "https://p.scdn.co/mp3-preview/9da9b99b3dcad027f1de434d2982c8e609cf1ea3?cid=905082a4b95b4c73815d97a4e9ba4798",
  "track_number": 5,
  "type": "track",
  "uri": "spotify:track:2MJADWCUllbjr5dtgwQDrw"
}"#;

fn main() -> color_eyre::Result<()> {
    let jd = &mut serde_json::Deserializer::from_str(source);
    match serde_path_to_error::deserialize(jd) {
        Ok(result) => {
            let result: Track = result;
            println!("{result:#?}");
        },
        Err(error) => {
            println!("{error}");
        }
    }
    Ok(())
}